# Generated by Django 6.0.6 on 2026-07-31 03:43

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0015_profile_marketing_attribution"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileActivationMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("recommendation_emitted", "Recommendation emitted"),
                            ("recommendation_accepted", "Recommendation accepted"),
                            ("first_project_created", "First project created"),
                            ("first_dataset_created", "First dataset created"),
                            (
                                "first_verified_indexed_row_update",
                                "First verified indexed row update",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activation_milestones",
                        to="core.profile",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("profile", "milestone"), name="unique_profile_activation_milestone"
                    )
                ],
            },
        ),
    ]
